apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zn-developercenter-ingress
  labels:
    app: zn-developercenter
    platform: redline
  annotations:
    external-dns.alpha.kubernetes.io/target: afaa6cd78a69ba99a.awsglobalaccelerator.com
    zalando.org/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:875929998342:certificate/10bb562c-267b-473c-830e-f8a00acea454
    zalando.org/skipper-ingress-redirect: "true"
spec:
  ingressClassName: skipper
  rules:
  - host: developercenter.hawking.dimebox.io
    http:
      paths:
      - backend:
          service:
            name: zn-developercenter-svc
            port:
              number: 80
        pathType: ImplementationSpecific