apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: zn-developercenter-hpa
  labels:
    app: zn-developercenter
    platform: redline
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zn-developercenter
  minReplicas: 2
  maxReplicas: 12
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 700Mi
  # - type: Pods
  #   pods:
  #     metricName: fe_legalconsent_k8s_scaling_requests_per_second_rate
  #     targetAverageValue: 300m
  # - type: Pods
  #   pods:
  #     metricName: fe_legalconsent_k8s_scaling_request_duration_seconds
  #     targetAverageValue: 3